demo_cart_homepage:
    path:     /
    defaults: { _controller: DemoCartBundle:Default:index }

demo_cart_product_create:
    path:     /product/create/{type}
    defaults: { _controller: DemoCartBundle:Product:create, type: shopping-item }
    requirements:
        type: shopping-item|sale-item

demo_cart_product_showall:
    path:     /product/list
    defaults: { _controller: DemoCartBundle:Product:listAll }

demo_cart_product_view:
    path:     /product/{id}
    defaults: { _controller: DemoCartBundle:Product:view }
    requirements:
            type: \d+