services:
#    demo_cart.example:
#        class: Demo\CartBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

#Entity managers
    demo_cart.cart_manager:
        class: Demo\CartBundle\Entity\Cart\CartManager
        arguments: ["@doctrine.orm.entity_manager","DemoCartBundle:Cart\OrderCart"]

    demo_cart.list_manager:
            class: Demo\CartBundle\Entity\Cart\ListManager
            arguments: ["@doctrine.orm.entity_manager","DemoCartBundle:Cart\WishList"]


    demo_cart.shopping_item_manager:
            class: Demo\CartBundle\Entity\Product\ShoppingItemManager
            arguments: ["@doctrine.orm.entity_manager","DemoCartBundle:Product\ShoppingItem"]

    demo_cart.order_item_manager:
                class: Demo\CartBundle\Entity\OrderElement\OrderItemManager
                arguments: ["@doctrine.orm.entity_manager","DemoCartBundle:OrderElement\OrderItem"]